### ISSUE TITLE
Need the most recent changes

### ISSUE THREAD

**Issue by dougarley** [whatsupnanap/week3project#1]
@whatsupnanap please push the most recent changes up to GitHub.

**Comment by whatsupnanap** [comment]
I'll do it noooow!

Sent from my iPhone

On Feb 15, 2015, at 1:09 AM, Doug Arley <notifications@github.com<mailto:notifications@github.com>> wrote:

Assigned #1https://github.com/whatsupnanap/week3project/issues/1 to @whatsupnanaphttps://github.com/whatsupnanap.

##

**Comment by dougarley** [comment]
Resolved by https://github.com/whatsupnanap/week3project/commit/96a7a172eaa7ec956bc425a24a6839c62b3edbdf

**Comment by whatsupnanap** [comment]
Each Dictionary or Array must be declared with at least 3 entries unless otherwise noted. If the types of something aren't specified you may use what you like.

Dictionary Declarations: - 2 Point(s)
-   Create a Dictionary using Strings for the Key and Ints for the Value.
-   Create a Dictionary using Strings for the Key and Floats for the Value.
  -   Declare this as an empty Dictionary
-   Create a Dictionary using Strings for the Key and Optional Strings for the Value.
-   Create a Dictionary using Strings for the Key and Tuples with Optional Types for the Value.
  -   Declare this as an empty Dictionary
-   Create a Dictionary using Strings for the Key and Arrays of Doubles for the Value.

Optional Declarations: - 2 Point(s)
-   Declare an Optional String Explicitly and give it a value in the declaration.
-   Declare an Optional Int Explicitly with no value.
-   Declare an Optional Tuple with 2 elements.
-   Declare a Tuple with 4 Optional elements.

Functionality:
-   Create a Dictionary that uses Strings for the Key's and Strings for the Values - 6 Point(s)
  -   The keys will be 2 letter State abbreviations.
  -   The values will be the full name of the associated State.
  -   Create the dictionary with 3 key/value entries
  -   Append an additional 2 entries
    -   Append once with the Subscript Method
    -   Append once with the correct Dictionary Method
    -   Update a value that exists in the dictionary
-   Create a Dictionary of String keys / Int values and create an Array of Strings - 10 Point(s)
  -   The int values must be a random number between 0 and 100
  -   The dictionary must contain a minimum of 25 entries.
  -   Auto Generate Key names in the format of "Key_##" where ## starts at 00, 01, 02, 03 etc.
  -   Declare the Array with the following value:
    -   ["Key_00", "Key_01", "Purple", "Key_100", "Key_05", "Key_10", "Key_25", "Key_15", "Test", "Key_20"]
  -   Using Optional Binding loop through the Array and check for that String key in the dictionary.
    -   If the Key is found and the value is even
      -   Update the value to 0 and print out the previous value.
    -   If the Key is found and the value is odd
      -   Remove that entry from the dictionary
    -   If the Key is not found, print out "Key (thekeyname) not found"

---

IMPORTANT REQUIREMENT NOTES

The application must be built for, compile, and launch on an iOS 8.0 or higher, 4.7" Device/Simulator.

Applications that do not compile will not receive credit.

Level of Effort

This activity should take approximately 160m to complete. It will require:
-   40m Research
-   0m Prep & Delivery
-   120m Work

---
